### ISSUE TITLE
[S4][P4] Message of receiver doesn't highlight 

### ISSUE THREAD

**Issue by daitrangA** [famivina/AntBuddy#36]
Assumpition:  hav conversation 1-1
1. User 1 : Send a message `@mention` or `@all`
2. User 2: Receive message and check this action

Actual: Message of receiver doesn't highlight
Expected: Message of receiver is highlight
![630](https://cloud.githubusercontent.com/assets/20940458/17881257/26522c4a-692e-11e6-912c-117c12400e87.png)

**Comment by qahtk3** [comment]
Not a bug. Close.
