### ISSUE TITLE
[Create New Company][S3][P3] Still allow user input number on "Domain" field

### ISSUE THREAD

**Issue by daitrangA** [famivina/AntBuddy#50]
1: User login successfully
2: Click on "Create new company" link 
3: Input vail "Company name"
4: Input number into "Domain" field 
5: Click on "Create" button and check this action

Actual: Create a new company successfully
Expected: Don't allow user input number on "Domain" field

Attach files
![1234](https://cloud.githubusercontent.com/assets/20940458/18040583/9232c262-6dd9-11e6-9e4e-87f6d37f5d4a.png)
![12345](https://cloud.githubusercontent.com/assets/20940458/18040584/971c9f50-6dd9-11e6-8f38-647b3ae7053a.png)

**Comment by qahtk3** [comment]
Not a bug.
